### ISSUE TITLE
QR code link to the training

### ISSUE THREAD

**Issue by jonathanpallant** [esp-rs/esp-rust-board#45]
Do you think you'd have space on the board for a QR code which links to the training material and/or other docs for the board?

**Comment by jonathanpallant** [comment]
Controversial thought perhaps, but seeing as the module on the top-side already has the Espressif logo on it, you could shrink the Espressif logo on the bottom-side to make room for a QR code.

**Comment by pedrominatel** [comment]
Hi @jonathanpallant!

Thanks for your suggestion!

I've some consideration regarding this:

- Boards are in production, we can't change anything now
- The silkscreen quality is not the best for small QR codes (considering the space we have)
- As an alternative, we can reduce the logo as you suggested and add a short link, not QR (similar to the GH link)
- QR as footprint with ENIG finishing
- Create a custom cardboard box with the links, QR code, logo, etc.

![image](https://user-images.githubusercontent.com/274658/170277472-6a302d2d-9514-4527-8c17-a540daae9659.png)

**Comment by jonathanpallant** [comment]
Putting the QR code or some other link on the box would be great. How were you planning on shipping/distributing the esp-rust boards?

**Comment by pedrominatel** [comment]
The same way Espressif does for any dev board. via distributors and directly for bulk.

**Comment by jonathanpallant** [comment]
Ah, I meant in an ESD bag or in a box like the ESP8684-DevKitM-1 pictured above?

**Comment by pedrominatel** [comment]
Sorry for the delay! I will depend. Both ways are possible.
