### ISSUE TITLE
board dimensions

### ISSUE THREAD

**Issue by kauly** [esp-rs/esp-rust-board#53]
I can't find the board dimensions anywhere, can you guys provide them?

**Comment by pedrominatel** [comment]
Hi,

PTAL here

https://github.com/esp-rs/esp-rust-board/blob/78a57479f640caded03caf177b8a1120efa5c862/hardware/esp-rust-board/schematic/esp-rust-board-Assembly.pdf

![image](https://user-images.githubusercontent.com/274658/200280872-e732e7b2-d1ca-4a86-b91d-4259461feb86.png)

**Comment by kauly** [comment]
thank you sir
